// Catalogo de produtos para o site
export const catalog = [
    {
      id: 1,
      name: "Lingerie Cinza",
      brand: "INSIDER",
      price: 135.88,
      fileImgName: "Product-1.jpeg",
      feminine: true,
    },
    {
      id: 2,
      name: "Vestido Preto",
      brand: "INSIDER",
      price: 80,
      fileImgName: "Product-2.jpeg",
      feminine: true,
    },
    {
      id: 3,
      name: "Camisa Marrom",
      brand: "INSIDER",
      price: 115,
      fileImgName: "Product-3.jpeg",
      masculine: true,
    },
    {
      id: 4,
      name: "Camisa Preta",
      brand: "INSIDER",
      price: 135,
      fileImgName: "Product-4.jpeg",
      masculine: true,
    },
    {
      id: 5,
      name: "Calcinha Minimal",
      brand: "INSIDER",
      price: 69,
      fileImgName: "Product-5.jpeg",
      feminine: true,
    },
    {
      id: 6,
      name: "Calça Always Ready Feminino",
      brand: "INSIDER",
      price: 649,
      fileImgName: "Product-6.jpeg",
      feminine: true,
    },
    {
      id: 7,
      name: "Tech T-Shirt Long Sleeve",
      brand: "INSIDER",
      price: 649,
      fileImgName: "Product-7.jpeg",
      masculine: true,
    },
    {
      id: 8,
      name: "Tech T-Shirt Long Sleeve Feminina",
      brand: "INSIDER",
      price: 189,
      fileImgName: "Product-8.jpeg",
      feminine: true,
    },
  ];